config {
    type: "table", // Assertion instead of table
    database: "sbx-edgar-dataform",
    schema: "austin_bikeshare",
    assertions: {
        rowConditions: [
            'deaths is not null and deaths > -1' // Here you can add your custom conditions
        ],
        nonNull: ["country_territory_code"],
        uniqueKeys: [
            ["date", "geo_id"],
            ["geo_id"]
        ]
    },
    tags: ["assertions"]
}

pre_operations{

    SELECT 1
}

SELECT
  *
FROM
  ${ref("covid19_ecdc_eu", "covid_19_geographic_distribution_worldwide")}


pre_operations{

    SELECT 2
}
