name: Pytest CI

on:
  push:
    paths:
      - dataform2looker/**
      - tests/**
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: "poetry.lock"
      - name: Install poetry
        run: pip install poetry
      - name: Install
        run: poetry install
      - name: Run tests with pytest
        run: |
          poetry run pytest -vv
